spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
        hikari:
            minimumIdle: 5
            maximumPoolSize: 20
            idleTimeout: 30000
            poolName: SpringBootJPAHikariCP
            maxLifetime: 2000000
            connectionTimeout: 30000
    jpa:
        hibernate:
            dll-auto: none
        generate-dll: true
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    liquibase:
        change-log: classpath:liquibase-changeLog.xml
        enabled: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: email@wypozyczalnia.pl
        password: haslo
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    task:
        scheduling:
            enabled: true
server:
    port: 8081

notification:
    manager-email: manager@wypozyczalnia.pl
    noreply-email: noreply@wypozyczalnia.pl
    system-email: system@wypozyczalnia.pl